version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: chordchart_pro_web
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./app:/usr/share/nginx/html:ro # Monta o diretório da app como somente leitura
